"use client";

import { useState } from "react";
import { STORY_TONES } from "@sentre/shared";

interface StoryResult {
  narrative: string;
  tone: string;
  generatedBy: string;
  sourceMemoryIds: string[];
}

export function StoryPanel({ productId }: { productId: string }) {
  const [tone, setTone] = useState<(typeof STORY_TONES)[number]>("nostalgic");
  const [story, setStory] = useState<StoryResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function generateStory() {
    setLoading(true);
    setError(null);
    try {
      const response = await fetch("/api/stories", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ productId, tone }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error ?? "Failed to generate story");
      setStory(data.story);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="mt-8 rounded-lg border border-zinc-200 p-5 dark:border-zinc-800">
      <h2 className="text-lg font-medium">Generate a story from real reviews</h2>
      <p className="mt-1 text-sm text-zinc-500">
        Retrieves this product&apos;s nostalgic reviews via RAG and turns them into a short narrative.
      </p>

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <select
          value={tone}
          onChange={(e) => setTone(e.target.value as (typeof STORY_TONES)[number])}
          className="rounded border border-zinc-300 bg-transparent px-2 py-1.5 text-sm dark:border-zinc-700"
        >
          {STORY_TONES.map((t) => (
            <option key={t} value={t}>
              {t}
            </option>
          ))}
        </select>
        <button
          onClick={generateStory}
          disabled={loading}
          className="rounded bg-zinc-900 px-4 py-1.5 text-sm text-white disabled:opacity-50 dark:bg-white dark:text-zinc-900"
        >
          {loading ? "Generating..." : "Generate story"}
        </button>
      </div>

      {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

      {story && (
        <div className="mt-4 rounded border border-zinc-200 bg-zinc-50 p-4 text-sm dark:border-zinc-800 dark:bg-zinc-900">
          <p className="italic">{story.narrative}</p>
          <p className="mt-2 text-xs text-zinc-500">
            {story.tone} · generated by {story.generatedBy} · grounded in {story.sourceMemoryIds.length} review(s)
          </p>
        </div>
      )}
    </section>
  );
}
